services:
  - type: web
    name: tangotube
    env: ruby
    region: frankfurt
    plan: starter
    numInstances: 1
    buildCommand: "./bin/render-build.sh"
    startCommand: REDIS_URL="redis://${REDIS_HOST}" bundle exec puma -C config/puma.rb
    domains:
      - tangotube.tv
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tangotube_production
          property: connectionString
      - key: REDIS_HOST
        fromService:
          name: tangotube-redis
          type: pserv
          property: hostport
      - key: RAILS_MASTER_KEY
        sync: false

    - type: worker
    name: tangotube-sidekiq
    env: ruby
    region: frankfurt
    plan: starter
    buildCommand: bundle install && bundle exec rake assets:precompile
    startCommand: REDIS_URL="redis://${REDIS_HOST}" bundle exec sidekiq -e production
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: myapp-db
          property: connectionString
      - key: REDIS_HOST
        fromService:
          name: tangotube-redis
          type: pserv
          property: hostport
      - key: RAILS_MASTER_KEY
        sync: false

    type: pserv
    name: tangotube-redis
    env: docker
    region: frankfurt # or oregon
    repo: https://github.com/render-examples/redis.git
    numInstances: 1
    disk:
      name: tangotube-redis-data
      mountPath: /var/lib/redis
      sizeGB: 1

databases:
  - name: tangotube_production
    plan: starter
    region: frankfurt

