databases:
  - name: tangotube
    databaseName: tangotube
    user: tangotube

services:
  - type: web
    name: tangotube
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tangotube_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
