databases:
  - name: tangotube_production
    databaseName: tangotube_production
    user: admin

services:
  - type: web
    name: tangotube
    env: ruby
    buildCommand: bundle install; bundle exec rake assets:precompile; bundle exec rake assets:clean;
    startCommand: bundle exec puma -t 5:5 -p ${PORT:-3000} -e ${RACK_ENV:-development}
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tangotube_production
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: sidekiq-redis
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

  - type: redis
    name: sidekiq-redis
    region: frankfurt
    maxmemoryPolicy: noeviction
    ipAllowList: [] # only allow internal connections

  - type: worker
    name: sidekiq-worker
    env: ruby
    region: frankfurt
    buildCommand: bundle install
    startCommand: bundle exec sidekiq
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: sidekiq-redis
          property: connectionString


