services:
  - type: web
    name: tangotube-web
    region: frankfurt
    plan: starter plus
    env: docker
    domains:
      - tangotube.tv
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tangotube-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: tangotube-redis
          type: redis
          property: connectionString
      - key: ELASTICSEARCH_URL
        fromService:
          name: tangotube-elasticsearch
          type: pserv
          property: hostport
      - key: RAILS_MASTER_KEY
        sync: false

  - type: worker
    name: tangotube-sidekiq
    region: frankfurt
    plan: starter plus
    env: docker
    dockerCommand: "bundle exec sidekiq"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tangotube-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: tangotube-redis
          type: redis
          property: connectionString
      - key: ELASTICSEARCH_URL
        fromService:
          name: tangotube-elasticsearch
          type: pserv
          property: hostport
      - key: RAILS_MASTER_KEY
        sync: false

  - type: cron
    name: tangotube-cron
    env: ruby
    region: frankfurt
    schedule: 0 3 * * *
    buildCommand: bundle install
    startCommand: >
      bundle exec rake update_all_channels
      && bundle exec update_all_videos
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: tangotube-redis
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: tangotube-db
          property: connectionString

  - name: tangotube-redis
    type: redis
    plan: starter
    region: frankfurt
    ipAllowList: []
    maxmemoryPolicy: allkeys-lru

  - type: pserv
    name: tangotube-elasticsearch
    env: docker
    dockerfilePath: "./elasticsearch/Dockerfile"
    region: frankfurt
    plan: standard
    disk:
      name: esdata
      mountPath: /usr/share/elasticsearch/data
      sizeGB: 10
    autoDeploy: false
    envVars:
    - key: ES_JAVA_OPTS
      value: "-Xms512m -Xmx512m"
    - key: discovery.type
      value: single-node
    - key: cluster.name
      value: elastic

databases:
  - name: tangotube-db
    plan: standard
    region: frankfurt
    ipAllowList: []
