services:
  - type: web
    name: tangotube-web
    region: frankfurt
    plan: starter plus
    env: ruby
    buildCommand: ./bin/render-build.sh
    startCommand: export PATH="$PATH:$HOME/project/src/yt-dlp"; bundle exec puma -C config/puma.rb
    domains:
      - tangotube.tv
    disk:
      name: data
      mountPath: /var/lib/data
      sizeGB: 5
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tangotube-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: tangotube-redis
          type: redis
          property: connectionString
      - fromGroup: tangotube-environment-group
      - key: MEILISEARCH_URL
        fromService:
          name: tangotube-meilisearch
          type: pserv
          property: hostport
      - key: MEILI_MASTER_KEY
        fromService:
          name: tangotube-meilisearch
          type: pserv
          envVarKey: MEILI_MASTER_KEY

  - type: worker
    name: tangotube-sidekiq
    region: frankfurt
    plan: standard
    env: ruby
    buildCommand: ./bin/render-build.sh
    startCommand: export PATH="$PATH:$HOME/project/src/yt-dlp"; bundle exec sidekiq -e production
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tangotube-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: tangotube-redis
          type: redis
          property: connectionString
      - fromGroup: tangotube-environment-group
      - key: MEILISEARCH_URL
        fromService:
          name: tangotube-meilisearch
          type: pserv
          property: hostport
      - key: MEILI_MASTER_KEY
        fromService:
          name: tangotube-meilisearch
          type: pserv
          envVarKey: MEILI_MASTER_KEY

  - type: cron
    name: tangotube-cron
    env: ruby
    region: frankfurt
    schedule: 0 3 * * *
    buildCommand: bundle install
    startCommand: >
      bundle exec rake performance:createPerformances

    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: tangotube-redis
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: tangotube-db
          property: connectionString
      - fromGroup: tangotube-environment-group
      - key: MEILI_MASTER_KEY
        fromService:
          name: tangotube-meilisearch
          type: pserv
          envVarKey: MEILI_MASTER_KEY

  - name: tangotube-redis
    type: redis
    plan: starter
    region: frankfurt
    ipAllowList:
      - source: "0.0.0.0/0"
        description: home
    maxmemoryPolicy: noeviction

  - type: pserv
    name: tangotube-meilisearch
    env: docker
    dockerfilePath: "./meilisearch/Dockerfile"
    region: frankfurt
    plan: standard
    disk:
      name: meili-data
      mountPath: /meili-data
      sizeGB: 50
    autoDeploy: false
    envVars:
    - key: MEILI_HTTP_ADDR
      value: 0.0.0.0:80
    - key: MEILI_MASTER_KEY
      generateValue: true
    - key: MEILI_DB_PATH
      value: /meili-data
    - key: MEILI_ENV
      value: production

databases:
  - name: tangotube-db
    plan: standard
    region: frankfurt
    ipAllowList:
      - source: "0.0.0.0/0"
        description: home

envVarGroups:
  - name: tangotube-environment-group
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
