development:
  :concurrency: 5
  :timeout: 500
production:
  :concurrency: <%= ENV["SIDEKIQ_CONCURRENCY_VALUE"] || 5 %>
  :timeout: 10
:queues:
  - high
  - mailers
  - searchkick
  - default
  - ahoy
